---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  serviceName: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: k8s.gcr.io/nginx-clim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - mountPath: my-app
              name: /opt/my-app
  volumeClaimTemplates:
    - metadata:
        name: my-app
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "my-storage-class"
        resources:
          requests:
            storage: 1Gi