---
#apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: my-app

resources:
  - ../../upstream/base/sts

patchesJson6902:
  - path: convert-to-deployment.json
    target:
      name: my-app
      kind: StatefulSet
      group: apps
      version: v1